<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- 封装设计 -->
    <!-- 属性封装 -->
    <xacro:property name="wheel_radius" value="0.0325"/> 
    <xacro:property name="wheel_length" value="0.0015"/> 
    <xacro:property name="PI" value="3.1415927"/> 
    <xacro:property name="base_link_length" value="0.08"/> 
    <xacro:property name="lidi_space" value="0.015"/> 

    <!-- 宏设计 -->
    <xacro:macro name="wheel_func" params="wheel_name flag">
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>

                <origin xyz="0.0 0.0 0.0" rpy="${PI/2} 0.0 0.0"/>

                <material name="wheel_color">
                    <color rgba="0.0 0.0 0.0 1.0"/>
                </material>
            </visual>            
        </link>

        <joint name="${wheel_name}2link" type="continuous">
            <origin xyz="0.0 ${0.1*flag} ${(base_link_length/2+lidi_space-wheel_radius)*-1}" rpy="0.0 0.0 0.0"/>
            <parent link="base_link"/>
            <child link="${wheel_name}_wheel"/>
            <axis xyz="0.0 1.0 0.0"/>
        </joint>
    </xacro:macro>

    <xacro:wheel_func wheel_name="left" flag="1"/>
    <xacro:wheel_func wheel_name="right" flag="-1"/>

</robot>